version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3002:5000" # Host:Container
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/tradingdb
    depends_on:
      - mongo

  frontend:
    build: ./dashboard
    container_name: frontend
    restart: always
    ports:
      - "3000:80" # Host:Container
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
