version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3002:3002"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start
    environment:
      - PORT=3002

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    command: npm start
    environment:
      - PORT=3000
